NAMA : Mohammad Hasan Basri

NIM  : 210411100169

MATA KULIAH : Pencarian dan Penambangan Web - A

# Tugas 7 : Klasifikasi Berita Metode Logistic Regression dengan reduksi dimensi deploy reduksi dimensi berita

Deploy Streamlit

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/PPWA/report/Tugas_PPWA/Hasil_Preprocessing_Hasan.csv")
df.head()

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,Iran Serukan Negara Muslim Bersatu Hentikan Ke...,"Kamis, 17 Okt 2024 10:01 WIB",Jakarta - Presiden Iran Masoud Pezeshkian mene...,Keislaman,Jakarta Presiden Iran Masoud Pezeshkian menek...,jakarta presiden iran masoud pezeshkian menek...,"['jakarta', 'presiden', 'iran', 'masoud', 'pez...",jakarta presiden iran masoud pezeshkian meneka...
1,"Bacaan Al-Qur'an Surah Asy-Syu'ara: Arab, Lati...","Kamis, 17 Okt 2024 09:30 WIB",NaN,Keislaman,NaN,NaN,['nan'],NaN
2,"Rukun Iman Ke-2, Setiap Muslim Wajib Mengimani...","Kamis, 17 Okt 2024 08:45 WIB",Jakarta - Malaikat adalah makhluk ciptaan Alla...,Keislaman,Jakarta Malaikat adalah makhluk ciptaan Allah...,jakarta malaikat adalah makhluk ciptaan allah...,"['jakarta', 'malaikat', 'adalah', 'makhluk', '...",jakarta malaikat makhluk ciptaan allah swt mus...
3,Kalender Ramadhan 2025 Muhammadiyah dan Predik...,"Kamis, 17 Okt 2024 08:00 WIB",Jakarta - Kalender Ramadhan 2025 versi Muhamma...,Keislaman,Jakarta Kalender Ramadhan versi Muhammadiyah...,jakarta kalender ramadhan versi muhammadiyah...,"['jakarta', 'kalender', 'ramadhan', 'versi', '...",jakarta kalender ramadhan versi muhammadiyah t...
4,20 Gambaran Kehidupan di Neraka Menurut Al-Qur...,"Kamis, 17 Okt 2024 07:15 WIB",Jakarta - Gambaran kehidupan di neraka selalu ...,Keislaman,Jakarta Gambaran kehidupan di neraka selalu m...,jakarta gambaran kehidupan di neraka selalu m...,"['jakarta', 'gambaran', 'kehidupan', 'di', 'ne...",jakarta gambaran kehidupan neraka pengingat ke...

Label Encoder

In [26]:
from sklearn.preprocessing import LabelEncoder

# Transformasi data kategorik
label_encoder = LabelEncoder()
df.loc[:, 'kategori_encoded'] = label_encoder.fit_transform(df['kategori'])

# Menampilkan nilai sebelum dan sesudah konversi
print("\nNilai sebelum dan sesudah konversi:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nDataFrame setelah Label Encoding:")
df

Nilai sebelum dan sesudah konversi:
{'Keislaman': 0, 'Pariwisata': 1}

DataFrame setelah Label Encoding:

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal,kategori_encoded
0,Iran Serukan Negara Muslim Bersatu Hentikan Ke...,"Kamis, 17 Okt 2024 10:01 WIB",Jakarta - Presiden Iran Masoud Pezeshkian mene...,Keislaman,Jakarta Presiden Iran Masoud Pezeshkian menek...,jakarta presiden iran masoud pezeshkian menek...,"['jakarta', 'presiden', 'iran', 'masoud', 'pez...",jakarta presiden iran masoud pezeshkian meneka...,0
1,"Bacaan Al-Qur'an Surah Asy-Syu'ara: Arab, Lati...","Kamis, 17 Okt 2024 09:30 WIB",NaN,Keislaman,NaN,NaN,['nan'],NaN,0
2,"Rukun Iman Ke-2, Setiap Muslim Wajib Mengimani...","Kamis, 17 Okt 2024 08:45 WIB",Jakarta - Malaikat adalah makhluk ciptaan Alla...,Keislaman,Jakarta Malaikat adalah makhluk ciptaan Allah...,jakarta malaikat adalah makhluk ciptaan allah...,"['jakarta', 'malaikat', 'adalah', 'makhluk', '...",jakarta malaikat makhluk ciptaan allah swt mus...,0
3,Kalender Ramadhan 2025 Muhammadiyah dan Predik...,"Kamis, 17 Okt 2024 08:00 WIB",Jakarta - Kalender Ramadhan 2025 versi Muhamma...,Keislaman,Jakarta Kalender Ramadhan versi Muhammadiyah...,jakarta kalender ramadhan versi muhammadiyah...,"['jakarta', 'kalender', 'ramadhan', 'versi', '...",jakarta kalender ramadhan versi muhammadiyah t...,0
4,20 Gambaran Kehidupan di Neraka Menurut Al-Qur...,"Kamis, 17 Okt 2024 07:15 WIB",Jakarta - Gambaran kehidupan di neraka selalu ...,Keislaman,Jakarta Gambaran kehidupan di neraka selalu m...,jakarta gambaran kehidupan di neraka selalu m...,"['jakarta', 'gambaran', 'kehidupan', 'di', 'ne...",jakarta gambaran kehidupan neraka pengingat ke...,0
...,...,...,...,...,...,...,...,...,...
95,"Praha Incar Turis-Turis Kaya, 'Wisata Pub Jala...","Rabu, 16 Okt 2024 06:13 WIB",Praha - Praha ingin mengganti imej dari kota s...,Pariwisata,Praha Praha ingin mengganti imej dari kota se...,praha praha ingin mengganti imej dari kota se...,"['praha', 'praha', 'ingin', 'mengganti', 'imej...",praha praha mengganti imej kota tujuan wisata ...,1
96,"Usai Festival Vegetarian, Phuket Pusing dengan...","Rabu, 16 Okt 2024 05:39 WIB",Phuket - Festival Vegetarian menjadi salah sat...,Pariwisata,Phuket Festival Vegetarian menjadi salah satu...,phuket festival vegetarian menjadi salah satu...,"['phuket', 'festival', 'vegetarian', 'menjadi'...",phuket festival vegetarian salah daya tarik pa...,1
97,Ngeri! Turis Inggris Tewas Saat Memanjat Jemba...,"Rabu, 16 Okt 2024 05:01 WIB",Jakarta - Seorang turis yang juga kreator kont...,Pariwisata,Jakarta Seorang turis yang juga kreator konte...,jakarta seorang turis yang juga kreator konte...,"['jakarta', 'seorang', 'turis', 'yang', 'juga'...",jakarta turis kreator konten inggris berusia t...,1
98,Info Loker: Lion Group Buka Lowongan Mekanik Nih!,"Selasa, 15 Okt 2024 23:04 WIB",Jakarta - Traveler yang ingin bekerja di dunia...,Pariwisata,Jakarta Traveler yang ingin bekerja di dunia ...,jakarta traveler yang ingin bekerja di dunia ...,"['jakarta', 'traveler', 'yang', 'ingin', 'beke...",jakarta traveler dunia aviasi baiknya simak in...,1
99,Pengumuman! KA Brantas dan KA Dharmawangsa Pak...,"Selasa, 15 Okt 2024 22:35 WIB",Jakarta - PT Kereta Api Indonesia (Persero) ak...,Pariwisata,Jakarta PT Kereta Api Indonesia Persero akan ...,jakarta pt kereta api indonesia persero akan ...,"['jakarta', 'pt', 'kereta', 'api', 'indonesia'...",jakarta pt kereta api indonesia persero mengop...,1

In [27]:
df

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal,kategori_encoded
0,Iran Serukan Negara Muslim Bersatu Hentikan Ke...,"Kamis, 17 Okt 2024 10:01 WIB",Jakarta - Presiden Iran Masoud Pezeshkian mene...,Keislaman,Jakarta Presiden Iran Masoud Pezeshkian menek...,jakarta presiden iran masoud pezeshkian menek...,"['jakarta', 'presiden', 'iran', 'masoud', 'pez...",jakarta presiden iran masoud pezeshkian meneka...,0
1,"Bacaan Al-Qur'an Surah Asy-Syu'ara: Arab, Lati...","Kamis, 17 Okt 2024 09:30 WIB",NaN,Keislaman,NaN,NaN,['nan'],NaN,0
2,"Rukun Iman Ke-2, Setiap Muslim Wajib Mengimani...","Kamis, 17 Okt 2024 08:45 WIB",Jakarta - Malaikat adalah makhluk ciptaan Alla...,Keislaman,Jakarta Malaikat adalah makhluk ciptaan Allah...,jakarta malaikat adalah makhluk ciptaan allah...,"['jakarta', 'malaikat', 'adalah', 'makhluk', '...",jakarta malaikat makhluk ciptaan allah swt mus...,0
3,Kalender Ramadhan 2025 Muhammadiyah dan Predik...,"Kamis, 17 Okt 2024 08:00 WIB",Jakarta - Kalender Ramadhan 2025 versi Muhamma...,Keislaman,Jakarta Kalender Ramadhan versi Muhammadiyah...,jakarta kalender ramadhan versi muhammadiyah...,"['jakarta', 'kalender', 'ramadhan', 'versi', '...",jakarta kalender ramadhan versi muhammadiyah t...,0
4,20 Gambaran Kehidupan di Neraka Menurut Al-Qur...,"Kamis, 17 Okt 2024 07:15 WIB",Jakarta - Gambaran kehidupan di neraka selalu ...,Keislaman,Jakarta Gambaran kehidupan di neraka selalu m...,jakarta gambaran kehidupan di neraka selalu m...,"['jakarta', 'gambaran', 'kehidupan', 'di', 'ne...",jakarta gambaran kehidupan neraka pengingat ke...,0
...,...,...,...,...,...,...,...,...,...
95,"Praha Incar Turis-Turis Kaya, 'Wisata Pub Jala...","Rabu, 16 Okt 2024 06:13 WIB",Praha - Praha ingin mengganti imej dari kota s...,Pariwisata,Praha Praha ingin mengganti imej dari kota se...,praha praha ingin mengganti imej dari kota se...,"['praha', 'praha', 'ingin', 'mengganti', 'imej...",praha praha mengganti imej kota tujuan wisata ...,1
96,"Usai Festival Vegetarian, Phuket Pusing dengan...","Rabu, 16 Okt 2024 05:39 WIB",Phuket - Festival Vegetarian menjadi salah sat...,Pariwisata,Phuket Festival Vegetarian menjadi salah satu...,phuket festival vegetarian menjadi salah satu...,"['phuket', 'festival', 'vegetarian', 'menjadi'...",phuket festival vegetarian salah daya tarik pa...,1
97,Ngeri! Turis Inggris Tewas Saat Memanjat Jemba...,"Rabu, 16 Okt 2024 05:01 WIB",Jakarta - Seorang turis yang juga kreator kont...,Pariwisata,Jakarta Seorang turis yang juga kreator konte...,jakarta seorang turis yang juga kreator konte...,"['jakarta', 'seorang', 'turis', 'yang', 'juga'...",jakarta turis kreator konten inggris berusia t...,1
98,Info Loker: Lion Group Buka Lowongan Mekanik Nih!,"Selasa, 15 Okt 2024 23:04 WIB",Jakarta - Traveler yang ingin bekerja di dunia...,Pariwisata,Jakarta Traveler yang ingin bekerja di dunia ...,jakarta traveler yang ingin bekerja di dunia ...,"['jakarta', 'traveler', 'yang', 'ingin', 'beke...",jakarta traveler dunia aviasi baiknya simak in...,1
99,Pengumuman! KA Brantas dan KA Dharmawangsa Pak...,"Selasa, 15 Okt 2024 22:35 WIB",Jakarta - PT Kereta Api Indonesia (Persero) ak...,Pariwisata,Jakarta PT Kereta Api Indonesia Persero akan ...,jakarta pt kereta api indonesia persero akan ...,"['jakarta', 'pt', 'kereta', 'api', 'indonesia'...",jakarta pt kereta api indonesia persero mengop...,1

In [28]:
# prompt: save df kedalam csv

df.to_csv('/content/drive/My Drive/PPWA/report/Tugas_PPWA/Hasil_Preprocessing_Hasan_encoded.csv', index=False)

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [30]:
# Memisahkan fitur dan label
x = df['stopword_removal']
y = df['kategori_encoded']

In [31]:
# Membagi data menjadi data latih dan data uji
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [32]:
# Replace NaN values with an empty string in the 'stopword_removal' column before TF-IDF
x_train = x_train.fillna('')
x_test = x_test.fillna('')

# Tahap 1: TF-IDF
tfidf_vectorizer = TfidfVectorizer()
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

# Mengonversi hasil TF-IDF menjadi DataFrame
df_train_tfidf = pd.DataFrame(x_train_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
df_test_tfidf = pd.DataFrame(x_test_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
print("Hasil TF-IDF (Data Latih):")
df_train_tfidf

Hasil TF-IDF (Data Latih):

,aamiin,ab,abaa,abaabiil,abaabiila,abad,abadi,abang,abbas,abdul,...,zhanni,zikir,zikri,zona,zoologi,zubkov,zulaikha,zulfi,zulhijah,zulkipli
0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.015982,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.039171,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.040932,0.04801,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
# Tahap 2: SVD (Reduksi Dimensi)
svd = TruncatedSVD(n_components=100, random_state=42)
x_train_svd = svd.fit_transform(x_train_tfidf)
x_test_svd = svd.transform(x_test_tfidf)

# Mengonversi hasil SVD menjadi DataFrame
df_train_svd = pd.DataFrame(x_train_svd)
df_test_svd = pd.DataFrame(x_test_svd)
print("\nHasil SVD (Data Latih):")
df_train_svd

Hasil SVD (Data Latih):

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,0.054160,0.013515,0.063212,0.022979,0.019349,0.116862,-0.102570,0.013876,0.078857,-0.232835,...,0.014496,0.000126,-0.005277,-0.008367,-0.009589,0.004915,-0.004717,-0.003903,0.000754,5.148372e-21
1,0.104339,0.081450,0.040230,-0.015368,0.021737,0.115788,-0.299070,0.211568,-0.017591,-0.150659,...,0.013400,-0.008719,-0.007076,0.002663,-0.004014,0.008117,-0.002483,-0.003314,0.000286,-2.722364e-18
2,0.150908,-0.059688,0.021550,-0.007741,0.054343,-0.014685,-0.061252,-0.130447,-0.194084,0.072495,...,-0.002162,0.029622,0.010645,0.003435,0.002753,0.002656,-0.003776,-0.001141,-0.005396,2.638481e-17
3,0.266381,-0.145265,-0.034098,0.016657,-0.015627,-0.013264,0.028101,-0.061207,0.194461,0.025530,...,0.002688,0.004426,0.015005,0.000452,-0.001925,0.002000,-0.004757,0.000820,-0.000449,-2.939959e-17
4,0.182932,0.358323,-0.060669,-0.013820,-0.043595,0.012126,-0.050943,0.023025,0.018709,0.339070,...,-0.126085,-0.010779,-0.002758,-0.004357,0.004444,0.003002,0.005966,0.028644,-0.001364,-1.395264e-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.182797,0.336787,-0.059238,0.041258,-0.026732,-0.000650,-0.081604,0.082875,0.017019,0.314211,...,-0.063770,0.000647,0.132477,-0.018137,-0.030833,-0.010584,0.000964,-0.003202,-0.000161,-2.503829e-18
76,0.070901,0.063424,0.170779,-0.010900,0.054779,0.404529,0.108677,-0.037845,0.018663,-0.038869,...,0.005631,0.013926,-0.029753,0.001604,0.007040,-0.051981,0.006860,-0.008191,0.001138,-9.404686e-18
77,0.206987,-0.099685,-0.012584,0.001633,0.005436,0.005435,-0.021216,0.052842,-0.015690,0.046610,...,0.007233,-0.015591,-0.006398,0.009351,0.002707,-0.006382,-0.001971,-0.001701,0.000242,-1.017795e-17
78,0.094105,0.066960,0.126422,0.018510,0.021014,0.225989,-0.198465,0.088758,0.033068,-0.355471,...,-0.044313,0.014950,0.011400,0.004851,0.001334,-0.013384,0.009262,0.009613,-0.000646,-3.574214e-18
79,0.095131,0.039295,0.121690,-0.038226,0.159494,-0.057549,-0.166652,0.049082,0.048026,0.026824,...,0.015041,-0.038209,0.020592,0.002880,-0.031761,-0.002361,-0.000008,-0.005790,0.001446,2.397717e-17

In [34]:
# Tahap 3: Klasifikasi dengan Logistic Regression
clf = LogisticRegression( random_state=42)
clf.fit(x_train_svd, y_train)
y_pred = clf.predict(x_test_svd)

In [35]:
# Evaluasi Model
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      1.00      0.89         8

    accuracy                           0.90        20
   macro avg       0.90      0.92      0.90        20
weighted avg       0.92      0.90      0.90        20

Pengujian

In [36]:
import joblib
from sklearn.pipeline import Pipeline

# Misalnya, Anda telah membuat pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('x_train_svd', TruncatedSVD(n_components=100)),
    ('clf', LogisticRegression())
])

# Setelah melatih model
pipeline.fit(x_train, y_train)

# Menyimpan pipeline
joblib.dump(pipeline, 'svd_tfidf_pipeline.pkl')

['svd_tfidf_pipeline.pkl']

In [37]:
import joblib
import pandas as pd

# Memuat pipeline yang telah disimpan
pipeline = joblib.load('svd_tfidf_pipeline.pkl')

# Teks baru yang ingin diprediksi
new_text_1 = ['''jakarta mimpi buruk lumrah dihindari manusia mimpi buruk mengalaminya merasakan cemas takut islam agama sempurna mendahulukan aktivitas berdoa terhindar mimpi buruk doa amalan umat islam rasulullah saw teladan umatnya menghindari mimpi buruk rasulullah saw bersabda bermimpi sukai allah hamdalah menceritakannya mimpi disukai setan berlindung kejahatannya menceritakannya niscaya berdampak buruk baginya hr albukhari hadits bermimpi menyenangkan memuji allah swt menceritakannya mimpi kenyataan memberitahukan mimpi buruk orang memohon perlindungan allah gangguan setan doa mimpi buruk doa diamalkan bermimpi buruk doa mimpi buruk mengutip buku tuntunan doa dzikir situasi kebutuhan karya ali akbar bin aqil doa bacaan latin allohumma inniazubika min amalis syaithoni wa sayyiatil ahlam ya allah berlindung kepadamu perbuatan setan buruknya mimpi doa mimpi buruk menukil buku doa mimpi buruk versi bacaan latin auudzu bikalimaatillaahittaammaati minghodhobihi wa iqoobihi wasyarri ibaadihi wamin hamazaatisysyayaathiini wa an yahdhuruu wa min hamajaatisysyayaatiini wa an yahduruun berlindung kalimat allah sempurna kemarahan siksaannya kejahatan hambahambanya godaan setan bisikannya hadir kepadaku doa mengharap mimpi menukil buku tiket surga doadoa mustajab karya abdul majid isfaudin doa mengharap mimpi bacaan latin allahumma arinal haqqa haqqan warzuqnat tibaaahu wa arinal baathila baathilan warzuqnajtina bahu ya allah tunjukkanlah kebenaran mengikutinya tunjukkanlah kejelekan menjauhinya amalan tidur mimpi buruk amalan umat islam kerjakan tidur amalanamalannya rasulullah tidur dikutip buku sunnah rasulullah seharihari karya syaikh abdullah bin hamoud al furaih wudhu tidur wudhu salah amalan sunnah dicontohkan rasulullah tidur termaktub hadits al bara bin azib nabi muhammad saw bersabda tidurmu berwudhulah wudhu sholat berbaringlah sisi kanan badanmu hr albukhari no muslim no membaca doa tidur amalan membaca doa tidur termaktub hadits diriwayatkan hudzaifah beliau nabi muhammad saw tidur beliau membaca doa bismika allahumma amutu waahya namamu ya allah mati hidup bangun tidur beliau berdoa alhamdulillahilladzi ahyana bada maa amatana wailaihinnusyur puji allah menghidupkan mematikan hr bukhari no mengibas kasur tidur muslim mengibas kasurnya hadits abu hurairah rasulullah saw bersabda tidur mengibas kasurnya sarungnya ucapkan latin bismika rabbi wadhatu janbii namamu tuhanku baringkan punggungku hr bukhari no muslim no membaca ayat kursi kaum muslim dianjurkan membaca ayat kursi tidur keutamaan membaca ayat kursi tidur perlindungan allah swt gangguan setan pagi diriwayatkan abu hurairah nabi muhammad saw membenarkan pernyataan berbaring tidurmu bacalah ayat kursi dengannya dijaga allah setan mendekatimu pagi hr bukhari dianjurkan menunda tidur isya rasulullah saw mencontohkan tidur isya maksud sahabat melewatkan ibadah utama sholat isya anjuran berdasarkan hadits diriwayatkan abu barzah nabi muhammad saw suka tidur sholat isya berbincangbincang setelahnya hr bukhari no muslim no berbaring miring kanan amalan rasulullah saw tidur berbaring miring kanan tidur rasulullah saw berbaring sisi kanannya ya allah menyerahkan diriku kepadamu mempercayakan urusanku kepadamu memalingkan wajahku kepadamu mengharapkan pahalamu takut hukumanmu mengandalkanmu lari darimu berlindung orang berlindung padamu percaya kitab engkau turunkan nabi engkau kirim hr bukhari hnhkri''']

new_text_2 = ['''jakarta krl rangkasbitung menghubungkan stasiun rangkasbitung banten stasiun tanah abang jakarta jalur transportasi pekerja rute memfasilitasi mobilitas masyarakat bepergian cepat kemacetan jalan raya bepergian stasiun rangkasbitung traveler stasiun dilewati jadwal keberangkatannya ketahui rute perjalanan transit stasiun tanah abang stasiun manggarai stasiun duri rute krl rangkasbitung transit jadwal keberangkatannya rute krl jabodetabek terbaru foto commuterlineid rute commuter line rangkasbitung melayani lintasan tujuan stasiun tanah abang stasiun merak stasiunstasiun rangkasbitungtanah abang traveler tanah abang stasiun jadwal keberangkatannya kereta berangkat rangkasbitung stasiun tanah abang laman commuter line jadwal keberangkatannya rutenya rangkasbitung citeras maja cikoya tigaraksa tenjo daru cilejit parung cicayur cisauk serpong rawa buntu sudimara jurang mangu pondok ranji kebayoran palmerah tanah abang rangkasbitungmerak tujuan stasiun merak traveler stasiun jadwal keberangkatannya dibandingkan kereta tanah abang keberangkatan rutenya rangkasbitung jambubaru catang cikeusal walantaka serang karangantu tonjongbaru cilegon krenceng merak rute krl rangkasbitung tujuan transit jalur stasiun tanah abang stasiun merak traveler transit stasiun tujuan rangkasbitungjakarta kota jakarta kota rangkasbitung transit melanjutkan perjalanan kereta begin kereta stasiun tanah abang turun stasiun tanah abang kereta stasiun manggarai stasiun manggarai lanjutkan perjalanan stasiun jakarta kota melewati pemberhentian stasiun jakarta kota rangkasbitungdepokbogor depok bogor traveler transit kali tanah abang manggarai kereta stasiun tanah abang turun stasiun tanah abang lanjutkan perjalanan kereta stasiun manggarai kereta arah depok bogor rangkasbitungbekasicikarang traveler bekasicikarang perjalanannya kereta stasiun tanah abang lanjutkan perjalanan stasiun manggarai kereta arah stasiun bekasicikarang rangkasbitungtangerang perjalanan tangerang traveler transit stasiun tanah abang duri rute perjalanannya kereta arah tanah abang teruskan perjalanan kereta arah duri stasiun duri kereta arah tangerang rute krl rangkasbitung jadwal keberangkatan rute perjalanan transit duri tanah abang manggarai elkrow''']

# Gabungkan kedua teks menjadi satu list
new_text = new_text_1 + new_text_2


# Melakukan prediksi dengan pipeline
predictions = pipeline.predict(new_text)

# Hasil prediksi
predicted_categories = ["Keislaman" if predictions ==  0 else "Pariwisata" for predictions in predictions]

# Output hasil prediksi untuk masing-masing teks
for i, category in enumerate(predicted_categories):
    print(f"Prediksi untuk teks {i+1}: {category}")

Prediksi untuk teks 1: Keislaman
Prediksi untuk teks 2: Pariwisata